apiVersion: v1
kind: PersistentVolume
metadata:
  name: compair-pv-1
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: compair-db-1
    fsType: ext4
