version: '2'
services:
  db:
    image: mariadb:10.1
    environment:
      - MYSQL_ROOT_PASSWORD=randompassword
      - MYSQL_DATABASE=compair
      - MYSQL_USER=compair
      - MYSQL_PASSWORD=compair
    volumes:
      - ./.data/mysql:/var/lib/mysql
    ports:
      - "13306:3306"
  redis:
    image: redis:3.2.4
    command: redis-server --appendonly yes
    volumes:
      - ./.data/redis:/data
    ports:
      - "16379:6379"
  app: &app
    image: ubcctlt/compair-app
    environment:
      - DB_DRIVER=mysql+pymysql
      - DB_USERNAME=compair
      - DB_PASSWORD=compair
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=compair
      - SQLALCHEMY_POOL_RECYCLE=299
      - DEV=1
      - CELERY_BROKER_URL=redis://redis:6379
      #- GA_TRACKING_ID=12345
      - ENFORCE_SSL=0
    volumes:
      - .:/code
      - ./.data/persistent:/code/persistent
    depends_on:
      - db
      - redis
  worker: &worker
    <<: *app
    command: celery worker --app=celery_worker.celery --loglevel=DEBUG
    environment: &worker_env
      - DB_DRIVER=mysql+pymysql
      - DB_USERNAME=compair
      - DB_PASSWORD=compair
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=compair
      - SQLALCHEMY_POOL_RECYCLE=299
      - DEV=1
      - CELERY_BROKER_URL=redis://redis:6379
      - C_FORCE_ROOT=1
      - ENFORCE_SSL=0
  worker_scheduler:
    <<: *worker
    command: celery beat --app=celery_worker.celery --loglevel=DEBUG
  web:
    image: nginx:1.11
    volumes:
      - ./deploy/docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./compair/static:/compair/app:ro
    ports:
      - "8080:80"
    depends_on:
      - app
